services:
  postgres:
    image: 'postgres:latest'
    container_name: 'db-bienestar-emocional'
    environment:
      - 'POSTGRES_DB=db_bienestar-emocional'
      - 'POSTGRES_PASSWORD=secret12345'
      - 'POSTGRES_USER=benitojuarez'
    ports:
      - '5433:5432'
